#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'André Dinis'
        hostname: ubuntu-desktop
        username: diolinux
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_PT.utf8
    keyboard:
        layout: pt
    timezone: "Europe/Lisbon"   
    packages:
        - steam
        - git
        - curl 
    snaps:
        - name: spotify
          channel: stable
          classic: false

        - name: Discord
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

